---
title: C28105 |Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 5
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 836a1571190a79579c47774e4dfd9c0aa0b508c7
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 08/22/2018
ms.locfileid: "47488937"
---
# <a name="c28105"></a>C28105
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

本主題的最新的版本可從[C28105](https://docs.microsoft.com/visualstudio/code-quality/c28105)。  
  
警告 C28105： 因例外狀況而流失資源  
  
 引發例外狀況時，不會釋放指定的資源。 路徑所指定的陳述式可以引發例外狀況。 這項警告是類似於警告[C28103](../code-quality/c28103.md)，不過在此情況下的相關例外狀況。  
  
## <a name="example"></a>範例  
 下列程式碼範例會產生此警告：  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 下列程式碼範例可避免此警告：  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```



