---
title: C6320
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 547b38734e08a09a27ea0857d964651bf6f2df78
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 01/02/2019
ms.locfileid: "53921267"
---
# <a name="c6320"></a>C6320
警告 C6320： 例外狀況篩選條件運算式是常數 EXCEPTION_EXECUTE_HANDLER。 這可能會遮罩所不能處理的例外狀況

 這則警告指出使用中的 EXCEPTION_EXECUTE_HANDLER 常數 __except 區塊的副作用。 在本例中的陳述式\__except 區塊一律會執行處理的例外狀況，包括您不想在特定函式中處理的例外狀況。 建議您檢查之前處理的例外狀況。

## <a name="example"></a>範例
 下列程式碼會產生這個警告，因為是 __except 區塊會嘗試處理所有類型的例外狀況：

```
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 若要更正這個警告，請使用`GetExceptionCode`檢查特定的例外狀況，再處理它，如下列程式碼所示：

```
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>另請參閱
 [try-except 陳述式](/cpp/cpp/try-except-statement)